### ISSUE TITLE
Flip Display Orientation

### ISSUE THREAD

**Issue by raf1312** [nopnop2002/esp-idf-ssd1306#11]
Hi,
On my lilygo Cam the Display is mounted upside down. 
Is there any easy solution to flip the image orientation 180°?

Thank you in advance. =)

**Comment by nopnop2002** [comment]
Try latest.

![config_flip](https://user-images.githubusercontent.com/6020549/115942613-0a77f880-a4e6-11eb-9b1d-48e5e82bf7fb.jpg)

![ssd1306_flip](https://user-images.githubusercontent.com/6020549/115942621-1794e780-a4e6-11eb-8873-62ffaad8f241.JPG)

**Comment by marchingband** [comment]
This doesn't work for me with an SPI display.

**Comment by nopnop2002** [comment]
@marchingband 
It's work for me.
![IMG_5810](https://github.com/user-attachments/assets/da4e9e54-b5a4-407d-9b96-bb35e44a0511)

**Comment by marchingband** [comment]
Turns out I have SH1106, for me it mirrors vertically, so the test is upside down compared to before, but also reversed.
Possibly just because its a different display?

**Comment by nopnop2002** [comment]
>Possibly just because its a different display?

I think it's because the hardware implementation is different from the standard SSD1306.

**Comment by marchingband** [comment]
interesting, this is a custom PCB from a client.
In any case I got u8g2 to work, so I am good now.
Let me know if there's anything I can do.

**Comment by nopnop2002** [comment]
There is a possibility that it will function correctly if you change the Memory Addressing Mode (20h), but I have not tried it.

```
	spi_master_write_command(dev, OLED_CMD_SET_MEMORY_ADDR_MODE);	// 20
	spi_master_write_command(dev, OLED_CMD_SET_PAGE_ADDR_MODE);		// 02
```
