### ISSUE TITLE
Make I2C Port also via Menuconfig configurable

### ISSUE THREAD

**Issue by DerPicknicker** [nopnop2002/esp-idf-ssd1306#23]
Hey, 

just a small Thing the I2C Hardware is not configurable via the Menuconfig but the SPI-Component is configurable. I found it in the Code so its not a big thing just a small improvement for future updates ;) 

Best regards

**Comment by nopnop2002** [comment]
The latest version addresses this issue.

**Comment by DerPicknicker** [comment]
Cool THANK YOU!!
