### ISSUE TITLE
Will it work with DS3231?

### ISSUE THREAD

**Issue by DerPicknicker** [nopnop2002/esp-idf-ssd1306#24]
Hi, 

you also have a DS3231 Library do you know it's working together with the ssd1306 OLED? I also created another issue [here](https://github.com/UncleRus/esp-idf-lib/issues/539) but I am sure that the issue belongs to the lib (I used different I2C Ports) 

So Could you test this for me or give me a hint how to combine the OLED with an DS3231?

Thank you in advance

**Comment by nopnop2002** [comment]
DS3231 is an i2c device.

The easiest way is to use ssd1306 from spi.

**Comment by DerPicknicker** [comment]
Hi @nopnop2002 , 

thank you for the detailed explanation. SPI would be a good choice but I don't have the pins for it. I2C is a must thing. Is there any way that you can make the display driver working with the uncle Russ or with your Ds3232 library you have in your GitHub account? I already use different Ports and not the same Hardware at the same time. The espS3 has two i2c ports so it should be possible to use one Rtc and one display with the s3. This would be really great. 

Is it possible to make it working using the 2 ports of the s3? I tried that already but it doesn't seem to work. I guess it will be easier to make the Rtc and the display independent. 

Many thanks and best regards

**Comment by nopnop2002** [comment]
If you change here, I feel like it will work.

https://github.com/nopnop2002/esp-idf-ssd1306/blob/master/components/ssd1306/ssd1306_i2c.c#L13

**Comment by DerPicknicker** [comment]
Hi again, 

I guess I already tried that.... I can double check it later. But I am to 90% sure that I changed it to 1 and let the Rtc to 0. This is why I am so curious.

**Comment by DerPicknicker** [comment]
@nopnop2002 .. 

I checked now the Code again and as I said. The Code uses different I2C Ports: 
Init the DS3231: 
<img width="461" alt="image" src="https://github.com/nopnop2002/esp-idf-ssd1306/assets/64746593/71fcc830-8502-4010-90d7-9c7874b27a0a">
and the I2C Port for the OLED Display: 
<img width="270" alt="image" src="https://github.com/nopnop2002/esp-idf-ssd1306/assets/64746593/910ee594-3b33-4780-baac-0dc192a80a9d">


And yes I tried it vice versa..... Do you have any Idea how to get this via I2C working?

**Comment by nopnop2002** [comment]
works fine.

```
    SSD1306_t dev2;
    ESP_LOGI(tag, "INTERFACE is i2c");
    ESP_LOGI(tag, "CONFIG_SDA_GPIO=%d",CONFIG_SDA_GPIO);
    ESP_LOGI(tag, "CONFIG_SCL_GPIO=%d",CONFIG_SCL_GPIO);
    ESP_LOGI(tag, "CONFIG_RESET_GPIO=%d",CONFIG_RESET_GPIO);
    i2c_master_init(&dev2, CONFIG_SDA_GPIO, CONFIG_SCL_GPIO, CONFIG_RESET_GPIO);
    ssd1306_init(&dev2, 128, 64);
    ssd1306_clear_screen(&dev2, false);
    ssd1306_contrast(&dev2, 0xff);

    i2c_dev_t dev;
    memset(&dev, 0, sizeof(i2c_dev_t));

    //ESP_ERROR_CHECK(ds3231_init_desc(&dev, 0, CONFIG_EXAMPLE_I2C_MASTER_SDA, CONFIG_EXAMPLE_I2C_MASTER_SCL));
    ESP_ERROR_CHECK(ds3231_init_desc(&dev, 1, CONFIG_EXAMPLE_I2C_MASTER_SDA, CONFIG_EXAMPLE_I2C_MASTER_SCL));
```

**Comment by DerPicknicker** [comment]
I will try it tomorrow

**Comment by nopnop2002** [comment]
The latest version allows you to specify the I2C port from the menu.
![config-i2c-port](https://github.com/nopnop2002/esp-idf-ssd1306/assets/6020549/df838a61-bb93-4bb1-a3cd-626f2b5a0f19)
