### ISSUE TITLE
Multiple displays

### ISSUE THREAD

**Issue by ko-bra** [nopnop2002/esp-idf-ssd1306#28]
Is there any way to use this to drive multiple displays?
In theory you could drive 4 displays with an ESP32 directly (2x i2c, 2x addresses).

Thanks for your help :)

**Comment by nopnop2002** [comment]
I don't know how to change the I2C address of ssd1306.

Devices with the same I2C address cannot connect to the same I2C bus.

When connecting multiple devices to one i2c bus, it is necessary to change the driver installation for the second and subsequent devices.

This will help.
https://docs.espressif.com/projects/esp-idf/en/stable/esp32/api-reference/peripherals/i2c.html

**Comment by nopnop2002** [comment]
I added MultiDeviceDemo Project.
