### ISSUE TITLE
i2c_new hardware scroll issue.

### ISSUE THREAD

**Issue by alexantony13** [nopnop2002/esp-idf-ssd1306#30]
In the ` components/ssd1306/ssd1306_i2c_new.c` file, in `i2c_hardware_scroll` function definition, wrong number of bytes is used in the `i2c_master_transmit` function call in line number 286.
`esp_err_t res = i2c_master_transmit(dev_handle, out_buf, 3, I2C_TICKS_TO_WAIT);`

Instead of:
`esp_err_t res = i2c_master_transmit(dev_handle, out_buf, out_index, I2C_TICKS_TO_WAIT);`

**Comment by nopnop2002** [comment]
Well, that's a wonderful discovery.
I didn't notice it at all.
thank you.
I fixed this bug.
