### ISSUE TITLE
Long text scrolling

### ISSUE THREAD

**Issue by alexantony13** [nopnop2002/esp-idf-ssd1306#32]
Is there any option to display a long text, which has characters greater than the display width, by scrolling?

**Comment by nopnop2002** [comment]
All you have to do is move the characters one by one and redraw them.

**Comment by alexantony13** [comment]
Thanks for the prompt reply.

I was looking for a method to show a dynamic notification bar at the bottom of the screen, say 1 page.
Needed to show details like IP address, connection status, etc.

Redrawing by after shifting one character at a time will work, but the scrolling wont be smooth. I think segment wise shifting should be used. Is this correct?

Is there any builtin methods in the library for this purpose?

**Comment by nopnop2002** [comment]
We understood what you want.
We plan to work on it on Monday night.

**Comment by nopnop2002** [comment]
Added this project.

https://github.com/nopnop2002/esp-idf-ssd1306/tree/master/TextBoxDemo

**Comment by alexantony13** [comment]
Thanks for the update.

The new feature works really well, for my purpose.
