### ISSUE TITLE
Support for various fonts

### ISSUE THREAD

**Issue by JayEnaR** [nopnop2002/esp-idf-ssd1306#36]
Is there a list somewhere of fonts that this library supports?

**Comment by nopnop2002** [comment]
Please refer to this.

https://github.com/nopnop2002/esp-idf-ssd1306/tree/master/BdfFontDemo

https://github.com/nopnop2002/esp-idf-ssd1306/tree/master/FreeTypeDemo

**Comment by JayEnaR** [comment]
Thanks for the response. I meant I wanted to use a different font for the `TextDemo`, but none of the hexadecimal arrays I've tried worked.

**Comment by nopnop2002** [comment]
All fonts here can be used.

https://github.com/dhepper/font8x8

**Comment by nopnop2002** [comment]
We have updated this.
https://github.com/nopnop2002/esp-idf-ssd1306/blob/master/TextDemo/README.md
