### ISSUE TITLE
Multi page

### ISSUE THREAD

**Issue by gsus24** [nopnop2002/esp-idf-ssd1306#39]
Thanks for sharing. Looks very promising for my project.

Is there a way to split the screen into pages like with TextBox or WrapAround to display BdfFont?
To update pages individually as needed!

For now i update the whole screen and each segment pops up successively.

Hope you can point me to right direction.

**Comment by nopnop2002** [comment]
I am unable to understand your request correctly.
Can you express it with a diagram or image?
