### ISSUE TITLE
Please specify a license

### ISSUE THREAD

**Issue by mordae** [nopnop2002/esp-idf-ssd1306#5]
The repository is missing a `LICENSE` file, preventing any kind of re-use.

Please consider using the same license as https://github.com/yanbe/ssd1306-esp-idf-i2c, that is [Apache License 2.0](https://github.com/yanbe/ssd1306-esp-idf-i2c/blob/master/LICENSE).

**Comment by nopnop2002** [comment]
Thank you very much for contacting me.
I have added a license.

**Comment by mordae** [comment]
Thanks a lot! I really appreciate your work. Working through various pieces of hardware and documenting how to effectively interact with them saves a lot of time for other people. I am looking forward to using your examples in my current project.
